"""Frame-source contracts, implementations, and latest-frame delivery."""

from .broker import BrokerMetrics, LatestFrameBroker
from .contracts import (
    CaptureSession,
    CaptureShutdownError,
    Clock,
    FrameSource,
    SourceError,
    SourceInfo,
    SourceLifecycleError,
    SourceOpenError,
    SourceReadError,
    SystemClock,
    VideoFrame,
)
from .fixtures import (
    FixtureAttempt,
    ReconnectFixture,
    disconnect_then_recover_fixture,
    make_preview_frame,
)
from .lifecycle import (
    ActiveCameraConflict,
    CameraRuntime,
    CameraRuntimeStatus,
    LifecycleState,
    ReconnectBackoff,
    RuntimeCounters,
    SourceFactory,
)
from .preview import encode_jpeg, multipart_chunk, preview_chunks
from .sources import (
    FakeFrameSource,
    FakeSource,
    PyAVFrameSource,
    PyAVRTSPSource,
    PyAVSource,
    RecordedFrame,
    RecordedSource,
    RecordedVideoSource,
    RTSPFrameSource,
)
from .worker import CaptureMetrics, CaptureWorker, FrameCaptureWorker

__all__ = [
    "BrokerMetrics",
    "ActiveCameraConflict",
    "CameraRuntime",
    "CameraRuntimeStatus",
    "CaptureMetrics",
    "CaptureSession",
    "CaptureShutdownError",
    "CaptureWorker",
    "Clock",
    "FakeSource",
    "FakeFrameSource",
    "FrameCaptureWorker",
    "FrameSource",
    "FixtureAttempt",
    "LifecycleState",
    "LatestFrameBroker",
    "ReconnectBackoff",
    "ReconnectFixture",
    "PyAVFrameSource",
    "PyAVSource",
    "PyAVRTSPSource",
    "RecordedSource",
    "RTSPFrameSource",
    "RecordedFrame",
    "RecordedVideoSource",
    "SourceError",
    "SourceInfo",
    "SourceLifecycleError",
    "SourceOpenError",
    "SourceReadError",
    "SourceFactory",
    "SystemClock",
    "RuntimeCounters",
    "VideoFrame",
    "disconnect_then_recover_fixture",
    "encode_jpeg",
    "make_preview_frame",
    "multipart_chunk",
    "preview_chunks",
]
