"""Live capture and inference coordination contracts."""

from .display import (
    LIVE_PROTOCOL_VERSION,
    DisplayBrokerMetrics,
    DisplayMessageTooLarge,
    DisplayProtocolError,
    ProcessedDisplayBroker,
    ProcessedDisplayCandidate,
    ProcessedDisplayEncoder,
    ProcessedDisplayService,
    ProcessedDisplaySubscription,
    ProcessedDisplayUnit,
    build_display_candidate,
    build_display_unit,
    jpeg_dimensions,
    validate_display_unit,
)
from .pipeline import (
    BackendFactory,
    EpochFactory,
    LiveFrameResult,
    LivePipelineConflict,
    LivePipelineCoordinator,
    LivePipelineError,
    LivePipelineFailure,
    LivePipelineMetrics,
    LivePipelineShutdownError,
    LivePipelineStatus,
    PipelineState,
    SourcePixelRegionOfInterest,
)

__all__ = [
    "BackendFactory",
    "DisplayBrokerMetrics",
    "DisplayMessageTooLarge",
    "DisplayProtocolError",
    "EpochFactory",
    "LIVE_PROTOCOL_VERSION",
    "LiveFrameResult",
    "LivePipelineConflict",
    "LivePipelineCoordinator",
    "LivePipelineError",
    "LivePipelineFailure",
    "LivePipelineMetrics",
    "LivePipelineShutdownError",
    "LivePipelineStatus",
    "PipelineState",
    "ProcessedDisplayBroker",
    "ProcessedDisplayCandidate",
    "ProcessedDisplayEncoder",
    "ProcessedDisplayService",
    "ProcessedDisplaySubscription",
    "ProcessedDisplayUnit",
    "SourcePixelRegionOfInterest",
    "build_display_candidate",
    "build_display_unit",
    "jpeg_dimensions",
    "validate_display_unit",
]
